app:
  name: stellar-http-example
  env: dev
  zone: local

http:
  server:
    enabled: true
    port: 8080
    adapter: gin
    observability:
      trace: true
      metrics: true
      logs: true

opentelemetry:
  log:
    enabled: false
    output: file
    dir: logs
    file_name: app.log
    max_size_bytes: 104857600
    max_backups: 5
  trace: false
  metrics: false
  trace_output: none
  metrics_output: prometheus
  metrics_path: /metrics
